"""
Constants for fraud detection and alerts
"""
FRAUD_REASONS = [
    'LARGE_TRANSACTION', 'UNUSUAL_LOCATION', 'RAPID_FREQUENCY',
    'INTERNATIONAL_FLAG', 'NIGHTTIME_ACTIVITY', 'SUSPICIOUS_MERCHANT',
    'MULTIPLE_DECLINES', 'ACCOUNT_TAKEOVER_SIGNALS', 'NEW_DEVICE_LOGIN',
    'UNUSUAL_BEHAVIOR_PATTERN', 'HIGH_RISK_COUNTRY'
]

ALERT_STATUSES = ['OPEN', 'IN_REVIEW', 'ESCALATED', 'RESOLVED', 'FALSE_POSITIVE', 'CONFIRMED_FRAUD']

SEVERITY_LEVELS = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']

DETECTION_METHODS = ['RULE_BASED', 'ML_MODEL', 'MANUAL_REVIEW', 'THIRD_PARTY', 'CUSTOMER_REPORTED']

FRAUD_TYPES = [
    'CARD_NOT_PRESENT', 'ACCOUNT_TAKEOVER', 'FRIENDLY_FRAUD',
    'IDENTITY_THEFT', 'MONEY_LAUNDERING', 'SYNTHETIC_IDENTITY'
]