"""
Constants for investment products and accounts
"""
INVESTMENT_TYPES = [
    'BROKERAGE', 'RETIREMENT_IRA', 'RETIREMENT_401K', 
    'MUTUAL_FUND', 'ETF_PORTFOLIO', 'TRADITIONAL'
]

RISK_TOLERANCE = ['LOW', 'MODERATE', 'HIGH', 'AGGRESSIVE']

ACCOUNT_STATUSES = ['ACTIVE', 'CLOSED', 'SUSPENDED', 'DORMANT']

INVESTMENT_STRATEGIES = [
    'GROWTH', 'VALUE', 'INCOME', 'BALANCED',
    'AGGRESSIVE_GROWTH', 'CONSERVATIVE', 'INDEX_MATCHING'
]

ASSET_CLASSES = [
    'EQUITIES', 'FIXED_INCOME', 'CASH', 'REAL_ESTATE',
    'COMMODITIES', 'ALTERNATIVES', 'CRYPTOCURRENCY'
]